export const ErrorCode = {
  INVALID_PARAMS: "INVALID_PARAMS",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  INVALID_EMAIL: "INVALID_EMAIL",
  INVALID_AGE: "INVALID_AGE",
  POST_NOT_FOUND: "POST_NOT_FOUND",
  PASSWORD_TOO_SMALL: "PASSWORD_TOO_SMALL",
  UNKNOWN: "UNKNOWN",
}
